### ISSUE TITLE
stand-along calculation of rule-set 3 (sequence) and rule-set3 (target + sequence)

### ISSUE THREAD

**Issue by maximilianh** [gpp-rnd/rs_dev#1]
Hi Peter, many thanks for making such an amazing repo available, including all the data. I'm sure countless authors will use this repo for at least a decade (I at least am still getting emails with questions on the Crispor repo and the data in it).

So, here comes yet another question: is there code here that allows it to calculate the rule-set 3 scores given a target sequence? I'm struggling to find an example... 

thanks!
Max

**Comment by PeterDeWeirdt** [comment]
Hi Max, good question. The rs3 repo in this org should be what you're looking for: https://github.com/gpp-rnd/rs3

**Comment by maximilianh** [comment]
Oops! Sorry, I didn't even see that. I saw it was referenced from the paper but the paper said that only features can be generated ("All of these features can be generated" with the rs3 packaged), but I should have looked at it anyways. Thanks!
